title:            爱者微语
description:      书锦难承殷意好 淤迂绮语声渐悄 会须期日心思巧 霁后烟虹 挈手星桥道
url:              http://Shy07.com # Site url.
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          Lynch # Your name.
disqus_shortname: lovewhisper # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics_id: UA-33540710-1 # set tracking, UA-XXXX-Y.

links:
  - name:         Home
    url:          http://Shy07.com
  - name:         About
    url:          /about.html
  - name:         Tour
    url:          /tour-de-memoire.html
  - name:         Feed
    url:          /feed.xml

pygments:         true
permalink:        /:year/:month/:title.html
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
