title:            L.A.
description:      L means Lynch, A is my Heroine.
url:              http://shy07.com # Site url.
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          Lynch # Your name.
disqus_shortname: lovewhisper# disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics_id: UA-33540710-1 # set tracking, UA-XXXX-Y.

links:
  - name:         关于
    url:          /about
  - name:         Feed
    url:          /feed.xml
  - name:         Email
    url:          mailto:Gernischt@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/Shy07
    external:     true

pygments:         true
permalink:        /:year/:month/:title.html
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
